apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: "{{ .Values.webapp.image }}:{{ .Values.webapp.tag }}"
          ports:
            - containerPort: {{ .Values.webapp.port }}
          env:
            - name: API_URL
              value: "http://api:{{ .Values.apiproxy.port }}"
